### ISSUE TITLE
Ch06 Snake: Apple is not generated with this code

### ISSUE THREAD

**Issue by SandroWissmann** [PacktPublishing/Mastering-Qt-5-Second-Editon#2]
![snake](https://user-images.githubusercontent.com/42449992/56861160-a249b700-699e-11e9-83d6-4644d66a2cd2.jpg)

I run this code with a windows machine and the apple doesnt get rendered. See screenshot.

In the Application Output i get:

> 10:14:45: Starting E:\Cpp_Projekte\QT\build-ch06-snake-Desktop_Qt_5_12_2_MSVC2017_32bit-Debug\debug\ch06-snake.exe ...
> QML debugging is enabled. Only use this in a safe environment.
> qml: Start game...
> [Qt3DRender::GLTexture] No QTextureData generated from Texture Generator yet. Texture will be invalid for this frame

**Comment by GuillaumeLazar** [comment]
It seems that you are using Qt 5.12.2. Did you try to compile the source code with Qt 5.11? (the Qt version used as the reference by the "Mastering Qt 5 - second edition" book).

Unfortunately, as you will discover, some core features of Qt3D are almost broke on each new Qt release version...
