### ISSUE TITLE
Ch-07 Third-Party Libraries without a Headache: - "Can not load library. The specified module can not be found"

### ISSUE THREAD

**Issue by wer14** [PacktPublishing/Mastering-Qt-5-Second-Editon#3]
Hello! I really enjoy reading this book. But the last TWO weeks I can not finish ch-7, my plugin does not want to load in qt designer AT ALL though I can run it like an app without a problem. I have built Open CV  32bit with MVC 2017 as well as Qt Creator but it keeps saying - "Can not load library. The specified module can not be found". I was trying to debug the plugin and load it using QPluginLoader with no luck it says - "Unknown Error".  I tried to build the app with qt 5.13.1 as well as 5.14.0 same error. Please advice what should I check one more time? I`m despaired.

**Comment by GuillaumeLazar** [comment]
Hi,
I'm glad that you enjoy the book :)

Concerning your Qt Designer plugin issue:  "Can not load library" means most of the time that a dependency of your plugin is not found (an OpenCV dll, a library required by OpenCV, ...).

As you develop on Windows OS you should try to use the free tool: Dependency Walker (http://www.dependencywalker.com). The "profile" mode can detect dynamic dependencies and the  missing one.
