### ISSUE TITLE
ch10 - IPC sample code issues

### ISSUE THREAD

**Issue by ysb530** [PacktPublishing/Mastering-Qt-5-Second-Editon#4]
If i run sample code of ch.10, it runs well if I use sample code of web site, 
but when I do it by myself, 
   1) 'Message.h' file not found', 
   2) 'JobResult.h' file not found, 
   3) 'Message.h' file not found,
   4) 'MessageUtils.h' file not found,
with warning "This file is not part of any project. The code might have issues to parse this file properly." in QtCreator. 

Anyway, i can see header files on "Other files", but they looks not linked with "mandelbrop-app" and "mandelbrot-worker.pro". 

I already added belows,  
"ch10-mandelbrot-ipc.pro"
OTHER_FILES += \
sdk/Message.h \
sdk/JobRequest.h \
sdk/JobResult.h \
sdk/MesssageUtils.h \

"mandelbrot-app.pro" & "mandelbrot-worker.pro"
INCLUDEPATH += $$PWD/../sdk
DEPENDPATH += $$PWD/../sdk

Please help me~~~

**Comment by GuillaumeLazar** [comment]
So you have a difference between the sample project and your project.

**1) Check the tree file of your project**
If you have extra directories or remove some directories, it will not work "out of the box".
```shell
.
├── ch10-mandelbrot-ipc.pro
├── mandelbrot-app
│   ├── main.cpp
│   ├── MainWindow.cpp
│   ├── MainWindow.h
│   ├── MainWindow.ui
│   ├── mandelbrot-app.pro
│   ├── MandelbrotCalculator.cpp
│   ├── MandelbrotCalculator.h
│   ├── MandelbrotWidget.cpp
│   ├── MandelbrotWidget.h
│   ├── WorkerClient.cpp
│   └── WorkerClient.h
├── mandelbrot-worker
│   ├── Job.cpp
│   ├── Job.h
│   ├── main.cpp
│   ├── mandelbrot-worker.pro
│   ├── Worker.cpp
│   ├── Worker.h
│   ├── WorkerWidget.cpp
│   └── WorkerWidget.h
└── sdk
    ├── JobRequest.h
    ├── JobResult.h
    ├── Message.h
    └── MessageUtils.h
```

**2) Put some log messages in .pro files to check the path**
* Then check if the include path / files exists really on your computer.
```shell
...
INCLUDEPATH += $$PWD/../sdk
DEPENDPATH += $$PWD/../sdk
message('Project PATH:' $$PWD)
...
```
It will print a log message when you do a qmake. e.g:
```shell
Project MESSAGE: Project PATH: /home/glazar/projects/Mastering-Qt-5-Second-Editon/Chapter10/mandelbrot-app
```

**3) Directory by directory replacing**
* Save your not-working project then try to replace directory by directory from the sample code.
* When the project is working, you can check with more focus the last replaced directory to find your mistake.

**Comment by ysb530** [comment]
Thanks, it works. (but, I don't know why it works suddenly. : ) )

I will use "message('Project PATH:' $$PWD)" when i meet issues. <-- very good advice for me.
