### ISSUE TITLE
CH06 - Support/instructions for Raspberry Pi 4

### ISSUE THREAD

**Issue by RoyeA** [PacktPublishing/Mastering-Qt-5-Second-Editon#5]
Are there instructions on how to follow chapter 6 for the Raspberry Pi 4?

**Comment by GuillaumeLazar** [comment]
It depends what you want to achieve. From easiest to hardest: 

### Play with Qt3D
- If you just want to play with Qt3D, you can follow the chapter 6 skipping the Raspberry Pi part and use only your desktop computer to run the software.

### Build on the Raspberry Pi
- If you want to also run it on your Raspberry Pi  without the "complicated" cross-compilation part. You can download Qt on your Raspberry Pi 4 and compile it directly on the Raspberry Pi 4. Like the Raspberry Pi was your devel computer.

### Cross-compilation for the Raspberry Pi
- If you want to achieve the cross-compilation part (build fast on your computer binaries runnable on the ARM processor of the Rasperry Pi). The theoretical inscrutions in the book are still correct but must be adapted. In any case, you need a sysroot of the target, the toolchain for the target, the Qt sources, build Qt for Rpi, configure a new kit for Qt creator, etc.
- I think you can learn a lot from my side project [QTRB](https://github.com/GuillaumeLazar/qtrb) that contains scripts to cross-compile Qt for a Raspberry Pi 3 step by step. 
- If you use QTRB for a Raspberry Pi 4, you must update the "config.sh" with a recent raspbian version and the file "30_configure_qt5_rpi.sh" to update the device parameter from "linux-rasp-pi3-g++" to something like "linux-rasp-pi4-v3d-g++".
- The device name "linux-rasp-pi4-v3d-g++" comes from the file [Qt mkspecs/devices](https://code.qt.io/cgit/qt/qtbase.git/tree/mkspecs/devices)
