### ISSUE TITLE
Update deprecated code with new syntax

### ISSUE THREAD

**Issue by stefanos82** [PacktPublishing/Mastering-Qt-5-Second-Editon#6]
The following lines are throwing warnings `'axisX' is deprecated` and `'axisY' is deprecated` about deprecated syntax: 

https://github.com/PacktPublishing/Mastering-Qt-5-Second-Editon/blob/858e53cc2d4879c2d27f3083ed60f74a345d88a3/Chapter02/MemoryWidget.cpp#L38-L40

We can replace these three aforementioned lines with the following code:

```c++
chart->axes(Qt::Horizontal).back()->setVisible(false);
chart->axes(Qt::Horizontal).back()->setRange(0, CHART_X_RANGE_MAX);
chart->axes(Qt::Vertical).back()->setRange(0, 100);
```

**Comment by GuillaumeLazar** [comment]
Hello @stefanos82,

Thank you for the message. Which version of Qt are you using?

**Comment by stefanos82** [comment]
I use version `5.15.2+dfsg-15` under GNU / Debian testing 64-bit.
